spring:
  application:
    name: hotel_reservation

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root


  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: houseoface81@gmail.com
    password: bfzoiiuarznjvgom
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  error:
    whitelabel:
      enabled: false
  port: 9090

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
